name: dejla
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # International phone numbers
  international_phone_input: ^1.0.3

  # Use the fontawesome icons
  font_awesome_flutter:

  # UI Library
  getflutter: ^1.0.11

  # Pin text field
  pin_input_text_field: ^3.0.1

  # More Icons
  flutter_icons:

  # Core of Firebase
  firebase_core:

  # Use the cloud firestore
  cloud_firestore:

  # Use the firebase authentication
  firebase_auth:

  # Use the firebase cloud storage
  firebase_storage:

  # Firebase Analytics
  firebase_analytics: ^5.0.11

  # Firebase GeoSearch
  geoflutterfire:

  # Open URL
  url_launcher: ^5.4.5

  # Geo locator check the current location and info
  #FIXME: IOS SETTING
  geolocator:

  # State Management
  provider:

  # Maps launcher
  maps_launcher: ^1.2.0

  # Image Cropper
  image_cropper:

  # carousel_slider
  carousel_slider: ^2.0.0

  # Sign In  buttons
  flutter_signin_button:

  # Progress buttons
  flutter_progress_button:

  # Circular profile avatar
  circular_profile_avatar:

  # Google Map
  google_maps_flutter:

  # RxDart
  # rxdart:

  # Alert
  rflutter_alert:

  # Image picker
  image_picker:

  # Loading
  flutter_spinkit:

  # Cache internet image
  cached_network_image:

  # Switch
  toggle_switch:

  # Image view
  photo_view: ^0.9.2

  # Get current package information
  # FIXME: For IOS only
  # https://pub.dev/packages/package_info#-readme-tab-
  package_info: ^0.4.0+13

  # Date range picker
  date_range_picker:

  # Data picker
  flutter_picker:

  # For google service
  uuid: ^2.0.4

  # HTTP client
  dio:
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
